### ISSUE TITLE
[HW] Riad Khan

### ISSUE THREAD

**Issue by gittingBetter** [datastaxdevs/workshop-vuejs#51]
**Name:** Riad Khan
**Email:** [REDACTED]
**Linkedin Profile:** [REDACTED]

Attach the homework screenshot below:
-----------------------------------------

![Untitled](https://user-images.githubusercontent.com/38712567/138156950-ae10f129-e751-4d2e-82d2-163524d814e6.png)

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Riad Khan

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/fOadl9_mSe6xDLyuuGwSvw

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>

**Comment by gittingBetter** [comment]
Thank you! Really looking forward to what other exciting things there are to learn.

**Comment by SonicDMG** [comment]
That's great. We have a ton of other workshops and you can do them all self-service if you wish. Is there something you are interested in? Maybe we have a workshop on the topic(s).

**Comment by gittingBetter** [comment]
I'm actually wondering whether there are any SRE workshops available. I saw that there were Cassandra tutorials on your site which I plan on going through.

**Comment by SonicDMG** [comment]
You know, that's a great question. I've asked the person who handles more of the ops end of things if we have any SRE material.

**Comment by SonicDMG** [comment]
Hi there. Ok, we don't have anything on the SRE end just yet, but they are coming. I would suggest to keep a watch on our YouTube channel or eventbrite.

**Comment by gittingBetter** [comment]
How exciting! I'll definitely be looking out for them. Thanks again for checking in on this.
