### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by palavallichaitanya** [datastaxdevs/workshop-vuejs#60]
**Name:** REPLACE_ME
**Email:** REPLACE_ME
**Linkedin Profile:** REPLACE_ME

Attach the homework screenshot below:
![image](https://user-images.githubusercontent.com/82885004/138284742-0333a648-79e5-4ed8-a933-23ea42671a18.png)

-----------------------------------------

<SCREENSHOT>

**Comment by SonicDMG** [comment]
Duplicate of https://github.com/datastaxdevs/workshop-vuejs/issues/61
